@startuml
title <size:24>Shared</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("SamliothekApplication_boundary", "SamliothekApplication", $tags="") {
  Container_Boundary("SamliothekApplication.SamliothekApplication_boundary", "SamliothekApplication", $tags="") {
    Component(SamliothekApplication.SamliothekApplication.Shared, "Shared", $techn="Module", $descr="", $tags="", $link="")
  }

}

SHOW_LEGEND(true)
hide stereotypes
@enduml