@startuml
title <size:24>Catalog</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("BibliothekApplication_boundary", "BibliothekApplication", $tags="") {
  Container_Boundary("BibliothekApplication.BibliothekApplication_boundary", "BibliothekApplication", $tags="") {
    Component(BibliothekApplication.BibliothekApplication.Catalog, "Catalog", $techn="Module", $descr="", $tags="", $link="")
  }

}

SHOW_LEGEND(true)
hide stereotypes
@enduml